artifact_location: file:///Users/macbook/Desktop/Python files/First deployed Project/mlruns/553655614246005379
creation_time: 1773276234615
experiment_id: '553655614246005379'
last_update_time: 1773276234615
lifecycle_stage: active
name: Diabetes_Prediction
workspace: default
